# Generated by Django 2.2.3 on 2019-08-24 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_f_new_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_new_posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 16, 52, 29, 195764, tzinfo=utc)),
        ),
    ]
