# Generated by Django 2.2.3 on 2019-08-24 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190824_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_new_posts',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
