# Generated by Django 2.2.4 on 2019-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190824_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_search_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
