# Generated by Django 2.2.4 on 2019-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_post_search_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_search_r',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
