# Generated by Django 2.2.4 on 2019-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catigoriez',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
