# Generated by Django 2.2.4 on 2019-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_post_catigoriez'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigoriez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigoriez', models.CharField(max_length=400)),
                ('post', models.CharField(max_length=400)),
            ],
        ),
    ]
