# Generated by Django 2.2.4 on 2019-09-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_catigoriez'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigoriez',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='catigoriez',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catigoriez',
            new_name='categories',
        ),
    ]
