# Generated by Django 2.2.4 on 2019-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
